name: Docker Image Scan

on:
  push:
    branches:
      - main

jobs:
  build-and-scan:
    runs-on: ubuntu-latest

    env:
      TERM: xterm

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker Image
        run: |
          echo "${{ secrets.DOCKER_PASSWORD_TOKEN }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker build . -t archana

      - name: Install Trivy
        run: |
          sudo apt-get install wget apt-transport-https gnupg lsb-release
          wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
          echo deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main | sudo tee -a /etc/apt/sources.list.d/trivy.list
          sudo apt-get update
          sudo apt-get install trivy
          clear
          trivy --version

      - name: Run Trivy and Convert to CSV
        run: |
          trivy image archana --format json > image-trivy-scan.json
          cat image-trivy-scan.json  # Troubleshooting step: Print JSON data
          echo "jq -r '(.[0] | keys_unsorted) as $keys | $keys, map([.[ $keys[] ]])[] | @csv' image-trivy-scan.json"  # Troubleshooting step: Print jq command

          # The `jq` command and subsequent operations will be performed here
          # Add error handling if required

      - name: Install Docker Scout
        run: |
          sudo apt update && sudo apt -y install curl
          mkdir -p ~/.docker/cli-plugins
          curl -sSfL https://raw.githubusercontent.com/docker/scout-cli/main/install.sh | sh -s --

      - name: Run Docker Scout CVE Scan
        run: |
          docker scout cves archana > image-cves-scan.csv
          cat image-cves-scan.csv
          
      - name: Checking Image Overview
        run: |
          docker scout quickview archana > image-scan-overview.csv
          cat image-scan-overview.csv
         
      - name: Send CVE Report via Email
        uses: dawidd6/action-send-mail@v2
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: '${{ secrets.EMAIL_USERNAME }}'
          password: '${{ secrets.EMAIL_PASSWORD }}'
          subject: CVE Report for Docker Image
          body: |
            Hello Friends 😇,
            
            Please find attached the CVE report and overview for the Docker image.
            Warm regards,
            Archana Kaushish
          to: kaushisharchana@gmail.com
          from: '${{ secrets.EMAIL_USERNAME }}'
          attachments: image-cves-scan.csv,image-scan-overview.csv,image-trivy-scan.csv
