name: Docker Image Scan

on:
  push:
    branches:
      - main

jobs:
  build-and-scan:
    runs-on: ubuntu-latest

    env:
      TERM: xterm

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker Image
        run: |
          echo "${{ secrets.DOCKER_PASSWORD_TOKEN }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker build . -t archana

      - name: Install Docker Scout
        run: |
          sudo apt update && sudo apt -y install curl
          mkdir -p ~/.docker/cli-plugins
          curl -sSfL https://raw.githubusercontent.com/docker/scout-cli/main/install.sh | sh -s --

      - name: Run Docker Scout CVE Scan
        run: |
          docker scout cves archana > image-cves-scan.csv
          cat image-cves-scan.csv
          
      - name: Checking Image Overview
        run: |
          docker scout quickview archana > image-scan-overview.csv
          cat image-scan-overview.csv
         
      - name: Send CVE Report via Email
        uses: dawidd6/action-send-mail@v2
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: '${{ secrets.EMAIL_USERNAME }}'
          password: '${{ secrets.EMAIL_PASSWORD }}'
          subject: CVE Report for Docker Image
          body: >
            Hello Friends 😇,

            Please find attached the CVE report and overview for the Docker
            image.
            Warm regards,
           Archana Kaushish
          to: archanakaushish@gmail.com
          from: '${{ secrets.EMAIL_USERNAME }}'
          attachments: image-cves-scan.csv,image-scan-overview.csv,image-trivy-scan.csv
